services:
  ha-fusion:
    container_name: ha-marick
    image: ghcr.io/marick45/test_ha1
    volumes:
      - /path/to/ha-marick:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://192.168.1.241:8123
    restart: always
